version: "3"
services:
  postgres:
    container_name: users-postgres
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: users-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge